name: golang-linting

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-dir: [app1, app2]  # List your application directories here
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Download golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Run golangci-lint
        run: |
          cd ${{ matrix.app-dir }}
          golangci-lint run --fix